package org.example.web;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.web.DefaultErrorAttributes;
import org.springframework.boot.autoconfigure.web.ErrorAttributes;
import org.springframework.boot.autoconfigure.web.ErrorController;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.context.request.RequestAttributes;
import org.springframework.web.context.request.ServletRequestAttributes;
import org.springframework.web.servlet.ModelAndView;

import com.marklogic.spring.http.proxy.HttpProxy;

/**
 * Controller that handles the login/logout endpoints expected by the UI generated by
 * https://github.com/marklogic/slush-marklogic-node. In addition, it also proxies all REST API requests to MarkLogic.
 */
@Controller
public class AppController implements ErrorController {

    protected final static Logger logger = LoggerFactory.getLogger(AppController.class);

    private final ErrorAttributes errorAttributes = new DefaultErrorAttributes();

    @Autowired
    private HttpProxy httpProxy;

    /**
     * Assumes that the root URL should use a template named "index", which presumably will setup the Angular app.
     */
    @RequestMapping(value = "/", method = RequestMethod.GET)
    public String index() {
        return "index";
    }

    /**
     * The UI checks the user's login status via this endpoint.
     */
    @RequestMapping(value = "/api/user/status", method = RequestMethod.GET)
    @ResponseBody
    public String userStatus(HttpServletResponse response) {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        response.setContentType("application/json");
        if (auth != null && auth.isAuthenticated()) {
            String username = null;
            if (auth.getPrincipal() instanceof User) {
                username = ((User) auth.getPrincipal()).getUsername();
            } else {
                username = auth.getPrincipal().toString();
            }
            return String.format("{\"authenticated\":true, \"username\":\"%s\"}", username);
        }
        return "{\"authenticated\":false}";
    }

    /**
     * Assumes that Spring Security is configured to use a custom form for a login page with a URL of "/login", with the
     * template for that form being named "login".
     */
    @RequestMapping(value = "/login", method = RequestMethod.GET)
    public String showLoginPage() {
        return "login";
    }

    /**
     * The UI logs the user out via this endpoint.
     */
    @RequestMapping(value = "/api/user/logout", method = RequestMethod.GET)
    @ResponseBody
    public void logout() {
        SecurityContextHolder.clearContext();
    }

    /**
     * Proxies all REST API requests to MarkLogic via an instance of HttpProxy.
     */
    @RequestMapping("/v1/**")
    @ResponseBody
    public void proxy(HttpServletRequest httpRequest, HttpServletResponse httpResponse) {
        httpProxy.proxy(httpRequest, httpResponse, "Content-type");
    }

    /**
     * System-wide error handler.
     * 
     * @param request
     * @return
     */
    @RequestMapping(value = "/error", produces = "text/html")
    public ModelAndView errorHtml(HttpServletRequest request) {
        RequestAttributes requestAttributes = new ServletRequestAttributes(request);
        Map<String, Object> map = this.errorAttributes.getErrorAttributes(requestAttributes, false);
        if (map.containsKey("status") && "404".equals(map.get("status").toString())) {
            // Show the index view, which should result in Angular processing the URL according to its routes.
            return new ModelAndView("index", map);
        }
        return new ModelAndView("error", map);
    }

    /**
     * Required by the ErrorController interface.
     */
    @Override
    public String getErrorPath() {
        return "/error";
    }

    public void setHttpProxy(HttpProxy httpProxy) {
        this.httpProxy = httpProxy;
    }

}
